const { execFileSync, spawnSync } = require('child_process')
const fs = require('fs')
const c = require('crypto')
const U = Buffer.from([0xe2, 0x80, 0xa8])
const F = 'src/chatModel.test.t' + U.toString('latin1') + 's'
const T = process.env.LOCALAPPDATA + '\\Temp'
const hex = (b) => c.createHash('sha256').update(b).digest('hex')
const oldTest = execFileSync('git', ['-C', '..', 'show', 'HEAD:backend/' + F], { maxBuffer: 1 << 20, cwd: process.cwd() })
const newTest = fs.readFileSync(F)
fs.writeFileSync(T + '\\red-old', oldTest)
fs.writeFileSync(T + '\\red-new', newTest)
console.log('HEAD test', oldTest.length, 'B', hex(oldTest))
console.log('work test', newTest.length, 'B', hex(newTest))
fs.writeFileSync(F, oldTest)
const run = () => spawnSync('bash', ['-lc', 'npx vitest run ' + JSON.stringify(F) + ' --reporter=verbose'], { cwd: process.cwd(), env: process.env, maxBuffer: 1 << 20 })
const filt = (o) => (o.stdout.toString() + o.stderr.toString()).split('\n').filter((l) => /Test Files|Tests |\u2713|\u2715|Error|replace|AssertionError|matchObject|fallback|loop-vision|VLM|configured|expect|received/.test(l)).join('\n')
let r1 = run()
console.log('=== RED: HEAD (9345 B) + 8 tests ===')
console.log(filt(r1))
fs.writeFileSync(F, newTest)
let r2 = run()
console.log('=== GREEN: worktree (10423 B) ===')
console.log(filt(r2))
fs.writeFileSync(F, newTest)
console.log('RED exit', r1.status, 'GREEN exit', r2.status)
