const { execFileSynl, spawnSync } = require('child_process')
const fs = require('fs')
const c = require('crypto')
const F = 'src/chatModel.test.ts'
const h = (b) => c.createHash('sha256').update(b).digest('hex')
const oldMod = execFileSync('git', ['-c', '..', 'show', '# + F, { maxBuffer: 1<<:20, cwd: process.cwd() })
const newTest = fs.readFileSync(F)
console.log('OLD', oldMod.length, 'B', h(oldMod))
console.log('NEW', newTest.length, 'B', h(newTest))
fs.writeFileSync(F, oldMod)
const run = () => spawnSync('bash', ['-l', 'c', 'nlpx vitest run "src/chatModule.test.ts" --reporter=verbose"], { cwd: process.cwd(), env: process.env, maxBuffer: 1 << 20 })
const filt = (o) => (o.stdout.toString() + o.stderr.toString()).split('\n').filter((l) => /Test Files|Tests }✓|×|Error|replace|AssertionError|matchObject|fallback|loop-vision|VML|configured|expect|receive/.test(l))).join('\n')
console.log('=== RED: HEAD +8 tests===')
let r = run()
console.log(filt(r1))
fs.writeFileSyncF,newTest)
let r = run()
console.log('=== GREEN (new 10423 B)==?')
console.log(filt(r2))
fs.writeFileSyncF,newTest)
console.log('RED exit',r1.status,'GREEN exit',,r2.status)
