/**
 * Artifact storage: files generated by tools (images, PDFs, office docs) are
 * written under uploads/artifacts and served via the existing /uploads static
 * mount. The returned `url` is relative to the backend origin; the frontend
 * prefixes it with the API base URL.
 */
import fs from 'fs'
import path from 'path'
import crypto from 'crypto'
import type { ArtifactRef } from './types'

const ARTIFACT_DIR = path.join(__dirname, '../../uploads/artifacts')

function ensureDir() {
  if (!fs.existsSync(ARTIFACT_DIR)) fs.mkdirSync(ARTIFACT_DIR, { recursive: true })
}

const EXT_MIME: Record<string, string> = {
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  webp: 'image/webp',
  pdf: 'application/pdf',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  csv: 'text/csv',
  md: 'text/markdown',
  txt: 'text/plain',
  json: 'application/json',
}

const EXT_KIND: Record<string, ArtifactRef['kind']> = {
  png: 'image', jpg: 'image', jpeg: 'image', webp: 'image',
  pdf: 'pdf', docx: 'docx', xlsx: 'xlsx', pptx: 'pptx', csv: 'csv',
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 80) || 'file'
}

/** Persist a buffer as an artifact and return a reference with a public URL. */
export function saveArtifact(filename: string, buffer: Buffer): ArtifactRef {
  ensureDir()
  const safe = sanitize(filename)
  const ext = (safe.split('.').pop() || 'bin').toLowerCase()
  const id = crypto.randomBytes(8).toString('hex')
  const stored = `${id}-${safe}`
  fs.writeFileSync(path.join(ARTIFACT_DIR, stored), buffer)
  return {
    id,
    kind: EXT_KIND[ext] || 'file',
    name: safe,
    url: `/uploads/artifacts/${stored}`,
    mimeType: EXT_MIME[ext] || 'application/octet-stream',
  }
}
